name: Deploy to GitHub Pages 
 
on:
  push:
    branches: [ main, master ]  # 触发分支 
 
jobs:
  build-deploy:
    runs-on: ubuntu-latest 
    permissions:
      contents: write 
      pages: write
      id-token: write 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
    
    - name: Setup Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # 推荐使用 LTS 版本[7]()[12]()
    
    - name: Install dependencies
      run: npm install
    
    - name: Build with Gulp 
      run: npm run build  # 执行 gulp 构建生成 dist 目录[1]()[3]()
    
    - name: Prepare deployment artifacts 
      run: |
        mv dist docs  # 重命名 dist 为 GitHub Pages 识别的目录 
        touch docs/.nojekyll  # 禁用 Jekyll 处理[4]()[5]()
    
    - name: Upload artifact 
      uses: actions/upload-pages-artifact@v3 
      with:
        path: 'docs/'  # 上传构建产物 
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4  # 官方部署组件[8]()[9]()
